# config.yml
openai:
  api-key: ""           # ← Paste your key here (or leave blank and set via env)
  model: "gpt-3.5-turbo" # default ChatGPT model
  timeout-ms: 60000      # how long to wait for a response
