name: CoreAI
version: '1.1.0'
main: be.stealingdapenta.coreai.CoreAI
api-version: '1.21'
load: STARTUP
authors: [StealingDaPenta]
description: An extensible, AI-powered Minecraft toolkit that brings in-game image generation, chat intelligence, and more to your server.
website: https://www.stealingdapenta.be

commands:
  chat:
    description: Chat with the AI
    usage: /<command> <message>
    permission: coreai.chat

  models:
    description: Select the AI model to use
    usage: /<command> <model>
    permission: coreai.models

  modelinfo:
    description: Show your current AI model and key info.
    usage: /<command>
    permission: coreai.modelinfo

  imagemap:
    description: Generate a map based on an image you provided
    usage: /<command> <prompt>
    permission: coreai.imagemap

permissions:
  coreai.setapikey:
    description: Allows setting your personal OpenAI API key
    default: true
  coreai.chat:
    description: Allows using /chat to talk with the AI
    default: true
  coreai.models:
    description: Allows selecting the AI model via GUI
    default: true
  coreai.modelinfo:
    description: Allows using /modelinfo to show your current AI model and key info
    default: true
  coreai.imagemap:
    description: Allows using /imagemap to generate an image from a prompt
    default: true
