name: CoreAI
version: '1.0-SNAPSHOT'
main: be.stealingdapenta.coreai.CoreAI
api-version: '1.21.5'
load: STARTUP
authors: [ StealingDaPenta ]
description: An extensible, AI-powered Minecraft toolkit that brings in-game image generation, chat intelligence, and more to your server.
website: https://www.stealingdapenta.be
