name: CoreAI
version: '1.0'
main: be.stealingdapenta.coreai.CoreAI
api-version: '1.21'
load: STARTUP
authors: [StealingDaPenta]
description: An extensible, AI-powered Minecraft toolkit that brings in-game image generation, chat intelligence, and more to your server.
website: https://www.stealingdapenta.be

commands:
  setapikey:
    description: Set your OpenAI API key (player-specific, encrypted)
    usage: /<command> <key>
    permission: coreai.setapikey

  chat:
    description: Chat with the AI
    usage: /<command> <message>
    permission: coreai.chat

permissions:
  coreai.setapikey:
    description: Allows players to set their personal API key
    default: true

  coreai.chat:
    description: Allows chatting with the AI
    default: true
